---
- hosts: all
  remote_user: root
  vars:
    terraform_version: 0.11.3
  

  tasks:
    # Note that we become superuser for installing apt packages
    - name: Install apt packages 
      become: true
      apt:
        # Perform the equivalent of an apt-update:
        update_cache: yes
        pkg: 
        - python3-apt
        - python3-pip
        - zsh
        - vim
        - tmux
        - git
        - htop
        - build-essential
        - stow
        - wget
        - curl
        - pass
        - unzip

        # Docker 
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

        # TODO: See if Pyenv will still work if we remove these deps
        - make 
        - libssl-dev 
        - zlib1g-dev 
        - libbz2-dev
        - libreadline-dev 
        - libsqlite3-dev 
        - llvm 
        - libncurses5-dev 
        - libncursesw5-dev
        - xz-utils 
        - tk-dev 
        - libffi-dev 
        - liblzma-dev 
        - python-openssl

    - name: Clone dotfiles repo
      git:
        key_file: ~/.ssh/id_rsa
        accept_hostkey: true
        repo: git@github.com:ranguli/gentoo.git
        dest: ~/dotfiles 

    - name: Stow dotfiles
      shell: cd ~/dotfiles && stow vim tmux ssh git zsh

    - name: Set zsh as the default shell
      become: true
      user:
        name: vagrant
        groups: admin, docker
        shell: /bin/zsh

    - name: Install Vim plugins 
      shell: vim +PlugInstall +qall

    - name: Do that docker thing 
      include: docker.yml
    
    - name: Do that node thing 
      include: nodejs.yml
    
    - name: Do that terraform thing 
      include: terraform.yml

    - name: Install some tools that are distributed via pip
      pip:
        executable: pip3
        name: 
        - awscli
        - pipenv

    - name: Install some tools that are distributed via npm
      become: true
      npm:
        global: true
        name: serverless
    
    - name: Add the Golang repository
      become: true
      apt_repository:
        repo: ppa:longsleep/golang-backports
        state: present

    - name: Install the Golang package
      become: true
      apt:
        name: golang-go
        update_cache: yes

    - name: Install pyenv
      shell: rm -fr ~/.pyenv && curl https://pyenv.run | bash

    - name: Install pyenv-virtualenv
      become: true
      git: 
        repo: https://github.com/pyenv/pyenv-virtualenv.git 
        dest: ~/.pyenv/plugins/pyenv-virtualenv


