---
- hosts: all
  remote_user: root

  tasks:
    # Note that we become superuser for installing apt packages
    - name: Install apt packages 
      become: true
      apt:
        # Perform the equivalent of an apt-update:
        update_cache: yes
        pkg: 
        - python3-apt
        - python3-pip
        - zsh
        - vim
        - tmux
        - git
        - htop
        - build-essential
        - stow
        - curl
        - pass

        # Docker 
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: Install oh-my-zsh
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

    - name: Clone dotfiles repo
      git:
        key_file: ~/.ssh/id_rsa
        accept_hostkey: true
        repo: git@github.com:ranguli/gentoo.git
        dest: ~/dotfiles 

    - name: Stow dotfiles
      shell: cd ~/dotfiles && stow vim tmux ssh git 

    - name: Install Vim plugins 
      shell: vim +PlugInstall +qall

    - name: Do that docker thing 
      include: docker.yml
    
    - name: Do that node thing 
      include: nodejs.yml

    - name: Install some tools that are distributed via pip
      pip:
        executable: pip3
        name:
          - awscli
    
    - name: Install some tools that are distributed via npm
      become: true
      npm:
        global: true
        name: serverless

    - name: Add the Golang repository
      become: true
      apt_repository:
        repo: ppa:longsleep/golang-backports
        state: present

    - name: Install the Golang package
      become: true
      apt:
        name: golang-go
        update_cache: yes

    - name: Install pyenv
      git:
        repo: https://github.com/pyenv/pyenv.git
        dist: ~/.pyenv
